(say "1..4")
(let ((ok (lambda (msg) (say "ok " msg)))
      (sum (lambda (a b) (+ a b)))
      (double (lambda (a) (* a 2))))
    (ok 1)
    (ok (double 1))
    (ok (sum 1 (double 1)))
    (ok (double (sum 1 1)))
)
